version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/:rw
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    command: bash -c "yarn install && yarn start"
