version: '2'
services:
  web:
    image: nginx:1.13.3
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
      - ../cert:/usr/share/nginx/cert
    ports:
      - "80:80"
      - "443:443"
