version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/:rw
      - ~/.ssh:/root/.ssh
    env_file:
      - configs.env
    ports:
      - "8080:8080"
    command: bash -c "yarn install && yarn start"
